public class ArithmeticException{
	public static void main(String[] args){
		try{
			int n1,n2,z;
			n1=10;
			n2=0;
			z=n1/n2;
			System.out.println("Done");
			}
		catch(java.lang.ArithmeticException e){
			System.out.println("Exception Handled:" +e);
			//e.printStackTrace();
			}
		}
	}



		###################################


import java.io.*;
public class ExceptTest{
	public static void main(String[] args){
		try{
			int a[]=new int[2];
			System.out.println("Access elements three:"+a[3]);

			}
		catch(ArrayIndexOutOfBoundsException e){
			//System.out.println("Exception thrown:"+e);
			e.printStackTrace();

			}
		System.out.println("Out of the block");
		}
	}